export type TBankName =
  | 'bKash'
  | 'Nagad'
  | 'Rocket'
  | 'dhakaBank'
  | 'BRACBank'
  | 'CityBank'
  | 'IslamiBank'
  | 'DBBL'
  | 'UttaraBank'
  | 'MutualTrustBank'
  | 'EasternBank'
  | 'StandardCharteredBank'
  | 'HSBC'
  | 'DutchBanglaBank'
  | 'SoutheastBank'
  | 'NationalBank';
